#!/usr/bin/env bash
# Script that configures an Ubuntu server to resolve localhost and facebook to different IP
echo "127.0.0.2 localhsot" > ~/hosts_new
echo "8.8.8.8 facebook.com" >> ~/host_new
tail -n +2 /etc/hosts >> ~/hosts_new
cp -f ~/hosts_new /etc/hosts
