#!/usr/bin/env bash
# Script that configures web-02 server
# shellcheck disable=SC2154

apt-get update
apt-get install -y nginx
service nginx restart
mkdir -p /var/www/html/
echo "Hello World!" | tee /var/www/html/index.html > /dev/null

redirect_url="https://github.com/mojalefakodisang"
host_name=$(hostname)
printf '%s\n' "server {
	listen 80;
	listen [::]:80;

	add_header X-Served-By \"$host_name\";

	server_name mojalefakodisang.tech www.mojalefakodisang.tech;
	root /var/www/html;
	index index.html index.htm;

	location /redirect_me {
		return 301 $redirect_url;
	}
}" > /etc/nginx/sites-available/default
service nginx restart
