#!/usr/bin/env bash
# Manages the process of manage_my_process script
argument="$1"
filename="manage_my_process"

if [ "$argument" = "start" ]; then
	sudo ./$filename &
	touch /var/run/my_process.pid
	echo "$!" > /var/run/my_process.pid
	echo "manage_my_process started"
elif [ "$argument" = "stop" ]; then
	kill "$(cat /var/run/my_process.pid)"
	sudo rm -f /var/run/my_process.pid
	echo "manage_my_process stopped"
elif [ "$argument" = "restart" ]; then
	kill "$(cat /var/run/my_process.pid)"
	sudo rm -f /var/run/my_process.pid
	./$filename &
	touch /var/run/my_process.pid
	echo "$!" > /var/run/my_process.pid
	echo "manage_my_process restarted"
else
	echo "Usage: manage_my_process {start|stop|restart}"
fi
