#!/usr/bin/env bash
# Displays FizzBuzz when number % 3 and 5
# Displays Fizz when number % 3
# Displays Buzz when number % 5
# els print number

for number in {1..100}
do
	if (( number % 3 == 0 && number % 5 == 0 ))
	then
		echo "FizzBuzz"
	elif (( number % 3 == 0 ))
	then
		echo "Fizz"
	elif (( number % 5 == 0))
	then
		echo "Buzz"
	else
		echo "$number"
	fi
done
