#!/usr/bin/env bash
# Displays "bad luck" at 4th iteration
# Displays "good luck" at 8th iteration
# Else displays "Best School"

count=1

while [ $count -le 10 ]
do
	if [ $count -eq 4 ]
	then
		echo "bad luck"
	elif [ $count -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	(( count++ ))
done
