#!/usr/bin/env bash
# Script that displays numbers from 1 to 20 and:
# displays 4 and then bad luck from China for the 4th loop iteration
# displays 9 and then bad luck from Japan for the 9th loop iteration
# displays 17 and then bad luck from Italy for the 17th loop iteration

counter=1

while [ $counter -le 20 ]
do
	echo "$counter"
	case "$counter" in
		"4") printf "bad luck from China\n" ;;
		"9") printf "bad luck from Japan\n" ;;
		"17") printf "bad luck from Italy\n" ;;
	esac
	((counter++))
done