#!/usr/bin/env bash
# Script that displays:
# The content of the current directory
# In a list format
# Where only the part of the name after the first dash is displayed

list=$(ls .)

list=${list//[0-9]-/""}
echo "$list"