#!/usr/bin/env bash
# Script that displays:
# The content of the current directory
# In a list format
# Where only the part of the name after the first dash is displayed

( ls . ) > list

for str in $(<list)
do
	str=${str//[0-9]-/""}
	echo "$str"
done
rm list